@startuml

title Specialty Use Case Diagram

'https://plantuml.com/use-case-diagram

left to right direction
'top to bottom direction

scale 1200 width

User - (Login)
package specialty {
    (Login) -> (Navigation)
    (Navigation) -> (Specialty.list)
    (Specialty.list) --> (Specialty.search)
    (Specialty.list) --> (Specialty.details)
    (Specialty.list) --> (Specialty.addNew)
    (Specialty.details) ---> (Specialty.edit)
    (Specialty.details) ---> (Specialty.delete)
}
@enduml